<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/12/23
 * Time: 12:29
 */
namespace backend\filters;

use yii\base\ActionFilter;

class CheckFilter extends ActionFilter
{
    public function beforeAction($action)
    {
//        return false;
        if(\Yii::$app->user->can($action->uniqueId)){

            return true;
//            return
        }
        echo '没有权限';
        return false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}