<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/12/24
 * Time: 13:37
 */

namespace backend\filters;


use backend\models\Article;
use yii\base\ActionFilter;

class TimeFilter extends ActionFilter
{
    public function beforeAction($action)
    {
        $histories = new Article();
        $histories->ip = $_SERVER["REMOTE_ADDR"];
        $histories->route = $action->id;
        $histories->time = time();
        $histories->save();
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}